### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Sitherious** [nguyenquyhy/DiscordBridge#37] opened 2016-12-30 04:58 UTC
can there be an option to disable this in console
but i would an option for it not to be displayed in console to help clear the clutter up, maybe have it in a debugging option or something?

> 
> 30.12 05:55:29 [Server] Websocket/INFO [de.btobastian.javacord.utils.DiscordWebsocketAdapter]: Reconnected!
> 30.12 05:55:29 [Server] WritingThread/INFO [de.btobastian.javacord.utils.DiscordWebsocketAdapter]: Trying to auto-reconnect...
> 30.12 05:55:29 [Server] WritingThread/INFO [de.btobastian.javacord.utils.DiscordWebsocketAdapter]: Websocket closed with reason null and code 1000 by server
> 30.12 05:54:53 [Server] Server thread/INFO [nucleus]: Server ran the command: /list 
> 30.12 05:54:33 [Server] Websocket/INFO [de.btobastian.javacord.utils.DiscordWebsocketAdapter]: Reconnected!
> 30.12 05:54:33 [Server] WritingThread/INFO [de.btobastian.javacord.utils.DiscordWebsocketAdapter]: Trying to auto-reconnect...
> 30.12 05:54:33 [Server] WritingThread/INFO [de.btobastian.javacord.utils.DiscordWebsocketAdapter]: Websocket closed with reason null and code 1000 by server

**Comment by Mohron** [comment] 2016-12-30 13:19
This is a bug. Duplicate of #33.

**Closed** 2017-01-05 04:32 UTC
